import Nav from '../components/Nav';
import Footer from '../components/Footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Metadata or other head tags go here */}
      </head>
      <body>
        
        {/* we put Nav and Footer inside body to not have hydration error :) */}
        <Nav />
        <hr></hr>
        PerSIsst Lab - Webpage Content
        <br></br>
        <br></br>
        {children}
        <hr></hr>
        <Footer />
      </body>
    </html>
  );
}
